/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -v -c QMaliitInputcontext1Adaptor -a qmcontextadaptor.h: interfaces/minputmethodcontext1interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef QMCONTEXTADAPTOR_H
#define QMCONTEXTADAPTOR_H

#include "qmnamespace.h"

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.meego.inputmethod.inputcontext1
 */
class QMaliitInputcontext1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.meego.inputmethod.inputcontext1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.meego.inputmethod.inputcontext1\">\n"
"    <method name=\"activationLostEvent\"/>\n"
"    <method name=\"imInitiatedHide\"/>\n"
"    <method name=\"commitString\">\n"
"      <arg type=\"s\"/>\n"
"      <arg type=\"i\"/>\n"
"      <arg type=\"i\"/>\n"
"      <arg type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"updatePreedit\">\n"
"      <annotation value=\"QList&lt;Maliit::PreeditTextFormat&gt;\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg type=\"s\"/>\n"
"      <arg type=\"a(iii)\"/>\n"
"      <arg type=\"i\"/>\n"
"      <arg type=\"i\"/>\n"
"      <arg type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"keyEvent\">\n"
"      <annotation value=\"Maliit::EventRequestType\" name=\"org.qtproject.QtDBus.QtTypeName.In6\"/>\n"
"      <arg type=\"i\"/>\n"
"      <arg type=\"i\"/>\n"
"      <arg type=\"i\"/>\n"
"      <arg type=\"s\"/>\n"
"      <arg type=\"b\"/>\n"
"      <arg type=\"i\"/>\n"
"      <arg type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"updateInputMethodArea\">\n"
"      <arg type=\"i\"/>\n"
"      <arg type=\"i\"/>\n"
"      <arg type=\"i\"/>\n"
"      <arg type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"setGlobalCorrectionEnabled\">\n"
"      <arg type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"preeditRectangle\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"setRedirectKeys\">\n"
"      <arg type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"setDetectableAutoRepeat\">\n"
"      <arg type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"setSelection\">\n"
"      <arg type=\"i\"/>\n"
"      <arg type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"selection\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"setLanguage\">\n"
"      <arg type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"notifyExtendedAttributeChanged\">\n"
"      <arg type=\"i\"/>\n"
"      <arg type=\"s\"/>\n"
"      <arg type=\"s\"/>\n"
"      <arg type=\"s\"/>\n"
"      <arg type=\"v\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    QMaliitInputcontext1Adaptor(QObject *parent);
    virtual ~QMaliitInputcontext1Adaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void activationLostEvent();
    void commitString(const QString &in0, int in1, int in2, int in3);
    void imInitiatedHide();
    void keyEvent(int in0, int in1, int in2, const QString &in3, bool in4, int in5, uchar in6);
    void notifyExtendedAttributeChanged(int in0, const QString &in1, const QString &in2, const QString &in3, const QDBusVariant &in4);
    bool preeditRectangle(int &out1, int &out2, int &out3, int &out4);
    bool selection(QString &out1);
    void setDetectableAutoRepeat(bool in0);
    void setGlobalCorrectionEnabled(bool in0);
    void setLanguage(const QString &in0);
    void setRedirectKeys(bool in0);
    void setSelection(int in0, int in1);
    void updateInputMethodArea(int in0, int in1, int in2, int in3);
    void updatePreedit(const QDBusMessage &message);
Q_SIGNALS: // SIGNALS
};

#endif
